foundry-rs/compilers

scripts/changelog.sh

We were missing this for `cargo release`.

fix: add changelog.sh

---

src/artifact_output/configurable.rs
src/artifact_output/mod.rs
src/artifacts/contract.rs
src/artifacts/mod.rs
src/hh.rs

chore: remove LosslessAbi

---

src/compile/output/mod.rs

This pull request proposes a change to the `ProjectCompileOutput` impl by creating a method `set_compiled_artifacts`. The modification is required for the usage of extending `foundry` to work with non-solc compilers like [`zksolc`](https://github.com/matter-labs/era-compiler-solidity/tree/main) for zkSync.
**Context:**
Currently, the `compiled_artifacts` field is marked as `pub(crate)`, making it accessible only within the same crate. This encapsulation poses a limitation when the struct is used as part of a larger build process where access to `compiled_artifacts` is needed to be modified. Providing a set method to update `compiled_artifacts` it the proposed solution. 
**Rationale:**
In effort to extend `foundry` support to zkSync ecosystem, the ability to set the modified Artifact is …

chore: add `set_compiled_artifacts` to ProjectCompileOutput impl

---

src/lib.rs
tests/project.rs

- Resolves https://github.com/foundry-rs/foundry/issues/5307
Currently, Foundry projects containing Solidity files outside the project root directory face contract verification failures on block explorers. This issue occurs from the Standard JSON including unusable source paths for external files, represented as full absolute paths in their host file systems.
This PR addresses the issue by improving the path conversion process. For files not located under the project root directory, relative parent directory paths (`..`) are used, enabling the compiler to find the files within the json.
Steps to reproduce the issue are detailed in the linked issue above. Additionally, a test case representing that scenario has been added.
With this change, the json created in the reproduction scenario …

fix: create verifiable Standard JSON for projects with external files

---

src/config.rs
src/utils.rs
tests/project.rs

Currently, when a project includes symbolic links to Solidity files, `Project::standard_json_input` returns a Standard JSON Input struct that is unusable for contract verification on block explorers. `solc` cannot compile these contracts based on the json, leading to verification failures. This pull request addresses this issue.
I encountered this problem when using the `forge verify-contract` command, which internally uses this function. While `forge build` completes successfully, the verification command fails, indicating that the block explorer cannot find a source file.
This problem occurs in projects that contain symlinked Solidity files and when these files are imported from other files. My project, structured as a monorepo, uses external libraries installed via pnpm. These …

fix: create valid Standard JSON to verify for projects with symlinks

---

src/lib.rs
src/project_util/mod.rs
tests/project.rs

To avoid boxing twice in case that an argument is already a box.

feat: use Box<dyn> in sparse functions

---

src/artifacts/mod.rs

highlighted by https://github.com/foundry-rs/foundry/issues/6707
field was introduced in 0.8.20
ref https://docs.soliditylang.org/en/latest/metadata.html

feat: add evmVersion to settings

---

src/cache.rs
src/resolver/mod.rs
tests/project.rs

Currently, dirty files discovery is not going deep enough into the graph, thus it often fails to discover all files that have dirty imports of some depth > 1. In worst case we may only recompile directly changed files and files directly importing them.
This PR changes this, so all files that have dirty files at some depth of their imports are marked as dirty.
This should solve a lot of weird issues with verification because it is very simple to occur such bug and it can result in, for example, script having and deploying outdated bytecode of contract which does not match the actual artifact.
If we would consider that problem as a graph theory problem, than we are dealing with oriented graph of `N` nodes representing files and `M` oriented edges between them representing imports. Some of …

Rewrite dirty files discovery

---

src/artifacts/mod.rs
src/compile/mod.rs

I believe this is all one has to do.
Note that this does not support `0.8.24` as a Solc version anywhere else other than the `EvmVersion` enum.
Closes https://github.com/foundry-rs/compilers/issues/46

feat: add EVM version Cancun

---

src/artifacts/contract.rs
src/compile/output/contracts.rs
src/compile/output/mod.rs
src/compile/output/sources.rs
src/lib.rs
tests/project.rs

There is no way to get the output by reference

chore: rename output to into_output

---

src/flatten.rs

Ref https://github.com/foundry-rs/foundry/pull/6936#issuecomment-1921443885
Not sure why exactly this unwrap is failing, adding `None` variant handling and some logs to debug it.

Flatten fix

---

src/artifacts/mod.rs
src/compile/output/mod.rs
src/compile/project.rs
src/lib.rs
src/project_util/mock.rs
src/project_util/mod.rs
tests/project.rs

[Related to #1200](https://github.com/foundry-rs/foundry/issues/1200)

Option to ignore warnings from dependencies in foundry.toml

---

Cargo.toml
src/config.rs
src/flatten.rs
src/resolver/mod.rs
test-data/test-flatten-duplicates/contracts/Bar.sol
test-data/test-flatten-duplicates/contracts/Foo.sol
test-data/test-flatten-duplicates/contracts/FooBar.sol
test-data/test-flatten-solang-failure/contracts/Contract.sol
test-data/test-flatten-solang-failure/contracts/Lib.sol
tests/project.rs

This PR implements two small flattener features mentioned in https://github.com/makerdao/spells-mainnet/pull/391#issuecomment-1926898173
1. Combine pragmas from different sources into one pragma so that version restrictions are kept the same before and after flattening
2. Comments specifying original source file of the flattened code (`// src/File.sol`)

Small flattener features

---

src/artifacts/error.rs
src/compile/output/mod.rs
tests/project.rs

closes https://github.com/foundry-rs/foundry/issues/5927
fixes a bug where severity::warning would ignore hard errors

fix: always treat errors as error

---

src/artifacts/output_selection.rs
src/cache.rs
src/config.rs

If the only difference between cached vs current solc config is `outputSelection` which is a subset of the cached output selection, then it's safe to use cached artifact.
I am currently adding logic to foundry to request only abi output and it would be nice if we could use cached abi where possible.
Impl is pretty ugly, but not sure how to make it better without cloning

feat: use cached artifacts if solc config is almost the same

---

src/artifact_output/configurable.rs
src/artifact_output/mod.rs
src/cache.rs
src/compile/project.rs
src/lib.rs

Resolves https://github.com/foundry-rs/foundry/issues/6241 
Removes `write_extra` logic from `ArtifactOutput` trait
Adds new methods:
- `handle_artifacts` - by default empty implementation which can be overloaded to implement handling of compiled artifacts. `ConfigurableArtifacts` implements it to write extra files
- `is_dirty` - method allowing `ArtifactOutput` implementations to reject cached artifacts and enforce recompilation. Used by `ConfigurableArtifacts` to reject artifacts which data is not enough to write required extra output files.
- `handle_cached_artifacts` - same as `handle_artifacts` but for those which were not recompiled. Used by `ConfigurableArtifacts` to write extra files from cached artifacts.

refactor: extra files logic

---

src/cache.rs
src/compile/project.rs
src/filter.rs
tests/project.rs

Currently we are not keeping cache entries for files which were out of scope of compiler (might be dirty or not)
Because of that, when running `forge compile`, then running `forge compile --skip ...` which will filter some artifacts out, and then running `forge compile` again, some artifacts will be recompiled, because `--skip` run removed those entries from cache.
Solution is to keep those entries in cache (we already silently keep artifacts anyway).

refactor: caching logic

---

src/artifacts/mod.rs

with 0.8.25 cancun is the default
https://github.com/ethereum/solidity/releases

fix: set evmversion::cancun as default

---

src/lib.rs

useful for compiling same project with different configs

chore: derive `Clone` for `Project`

---

src/artifacts/mod.rs

feat: optimization field (simpleCounterForLoopUncheckedIncrement)

---

src/cache.rs
src/compile/project.rs

Follow-up to #104. Right now we detect and remove dirty cache entries in `ArtifactsCacheInner::filter` which is redundant as we can just do a single iteration over all cached files.
Now file filtering is done in 2 steps:
1. `ArtifactsCacheInner::find_and_remove_dirty` detects all dirty entries (even those that are not in scope of current compiler run) and removes them from cache.
2. `ArtifactsCacheInner::filter` schedules for compilation all sources for which we are missing artifacts (either because of removed entry or because we never compiled given source with current version)

fix: dirty files detection

---

Cargo.toml
src/artifacts/error.rs

Ref https://github.com/foundry-rs/foundry/issues/7709

Update yansi to 1.0

---

src/artifacts/mod.rs

closes https://github.com/foundry-rs/block-explorers/issues/38

fix: use serde default for optimizer

---

src/lib.rs

closes https://github.com/foundry-rs/foundry/issues/7811
prevents accidentally deleting the root folder

fix: add checks for != root folder

---

src/remappings.rs

closes https://github.com/foundry-rs/foundry/issues/7820
pnpm setups can contain symlink loops, we need to track visited symlink dirs and short circuit if we already visited a symlink dir

fix: short-circuit symlink cycle

---

src/artifacts/mod.rs
src/compile/project.rs
src/compilers/mod.rs
src/compilers/solc/mod.rs
src/compilers/vyper/input.rs
src/compilers/vyper/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/7878
Removes paths stripping logic from solc implementation, instead we now use `CompilerInput::strip_prefix` and `CompilerOutput::join_all` directly in `compile_*` functions, and only join output paths after writing build info.

fix: absolute paths in build info

---

src/artifacts/mod.rs
src/compile/mod.rs
src/compilers/solc/version_manager.rs

Closes #119
these got lost while moving more stuff to versionmanager, however the finding an installed versioned based on the requirement alone is still useful and should be preserved.
This can still be pushed to version manager, but we should keep it on Solc directly as well

feat: add a few Solc install helpers back

---

src/artifacts/mod.rs
src/compilers/solc/mod.rs
tests/project.rs

Closes https://github.com/foundry-rs/foundry/issues/7869

fix: re-enable yul settings sanitization

---

src/cache.rs
src/compile/project.rs
src/compilers/vyper/error.rs
src/compilers/vyper/mod.rs
src/compilers/vyper/settings.rs
src/lib.rs
src/project_util/mod.rs
tests/project.rs

Changes order of generics on `Project`. We'll be doing a lot of `Project<C>` and most of the time we use the same `ConfigurableArtifacts`

chore: swap generics on `Project`

---

Cargo.toml
src/compilers/mod.rs
src/compilers/solc/mod.rs
src/compilers/vyper/input.rs
src/compilers/vyper/parser.rs
src/compilers/vyper/settings.rs
src/filter.rs
src/resolver/mod.rs

We need to parse Vyper import directives for caching to work correctly.
This PR implements parser which is able to process imports of format `import a.b.c` and `from a.b.c import d`. Relative imports (`from ...a.b.c import d`) are also supported.
Tested on snekmate codebase.

feat: Vyper imports parser

---

deny.toml
src/compile/output/mod.rs
src/compilers/mod.rs

Updates trait bounds to make it easier to work with `ProjectCompileOutput` on foundry side

fix: relax trait bounds

---

src/compilers/vyper/parser.rs
src/lib.rs
test-data/vyper-imports/src/A.vy
test-data/vyper-imports/src/B.vy
test-data/vyper-imports/src/module/C.vy
test-data/vyper-imports/src/module/inner/E.vy
test-data/vyper-imports/src/module/inner/F.vy
tests/project.rs

Current Vyper path resolution does not correctly handle relative paths (`from . import X`, `from .. import X`).
This PR fixes this and changes parser to parse into `VyperImport` which tracks `final_part` (X at `from ... import X` expression).
Currently vyper allows doing imports like `from Contract import Contract` which is equivalent to `import Contract as Contract` and only requires `Contract.vy` to be present. However, such format is only supported when invoking `vyper` from command like, and for standard JSON input it does not work, which is why we can't compile snekmate right away without small import fixes.
I believe in the future Vyper versions that will be fixed and thus `VyperImport` tracks `final_part` additionaly.
Also added more tests for path resolution

fix: update vyper path resolution logic

---

Cargo.toml
src/compile/project.rs
src/compilers/mod.rs
src/compilers/multi.rs
src/compilers/solc.rs
src/filter.rs
src/lib.rs
src/project_util/mod.rs
tests/project.rs

better approach for https://github.com/foundry-rs/foundry/pull/8061
We already keep all compilation settings on `Project` (paths, compier settings, compiler itself), so this PR moves `sparse_output` to `Project` as well to allow us to just configure it in `Config::project` instead of adding it to compiler on every invocation in multiple places.
Also this PR gets rid of separate `SparseOutputFileFilter<D>` trait and makes `sparse_output` filter just a `FileFilter` again. Instead, we now have `ParsedSource::compilation_dependencies` which determines which of the source imports must be compiled along with it.
Simplified some sparse output related logic along with changes.
Due to `Box<dyn FileFilter>` on `Project` this PR adds `dyn-clone` to keep `Clone` impl and `derivative` to avoid …

refactor: sparse output

---

src/compile/project.rs
src/compilers/mod.rs
src/compilers/vyper/output.rs
src/compilers/vyper/settings.rs
src/filter.rs
tests/project.rs

Ensure that input and output only contains sources filtered out by sparse output filter, if present. This is needed to avoid optimized artifacts without abi and bytecode ending up in cache.

fix: small sparse output updates

---

src/cache.rs
src/compile/project.rs

Currently, during sparse compilation (and probably in some other cases) we might end up in a situation when cache contains empty entries which can actually produce artifacts when compied.
For example, if A.sol imports B.sol and sparse filter tells us to only compile A.sol, then B.sol will appear in cache (because we have to track its source hash to invalidate A.sol's cache), however, we will erase its output selection when invoking solc, so it will not have any artifacts.
Thus, if compiler is invoked later without sparse filter, it will simply skip compiling B.sol because it will assume that it just does not contain any contract definitions: https://github.com/foundry-rs/compilers/blob/4cf78434b21481c78a8236c95ac82eb945a01758/src/cache.rs#L658-L663
Because of that, artifact for B.sol will …

fix: better tracking of cache entries

---

src/artifacts/mod.rs

Follow-up to https://github.com/foundry-rs/compilers/pull/108.
It seems that in certain cases files on WSL still have `\r\n` prefix, thus this PR changes logic to always fix Windows line endings and not only on Windows builds.

fix: always fix windows line endings

---

deny.toml
src/artifact_output/mod.rs
src/artifacts/mod.rs
src/buildinfo.rs
src/cache.rs
src/compile/output/contracts.rs
src/compile/output/mod.rs
src/compile/output/sources.rs
src/compile/project.rs
src/compilers/mod.rs
src/compilers/multi.rs
src/compilers/solc.rs
src/compilers/vyper/error.rs
src/compilers/vyper/input.rs
src/compilers/vyper/mod.rs
src/flatten.rs
src/lib.rs
src/project_util/mod.rs
tests/project.rs

ref https://github.com/foundry-rs/foundry/issues/7379
ref https://github.com/foundry-rs/foundry/issues/4981
ref https://github.com/foundry-rs/foundry/issues/2704
The way Solidity assigns `source_id`s is simply by order in which sources are passed in compiler input. Thus, if we have two sources `A.sol` and `B.sol`, then on the first (non-cached) compiler run, `A.sol` will get assigned ID 1 and `B.sol` will have ID 2.
Then, if we change `B.sol` slightly and recompile, it will be the only source in the input, so it will have ID 1.
The same ID collisions are more often appearing on multi-version and multi-compiler builds. After many cached runs such discrepancies result in debugger basically displaying random sources.
This PR adds a way to link an artifact to the build info for input that …

feat: track and cache context of each compiler invocation

---

crates/artifacts/solc/src/ast/mod.rs
crates/compilers/src/compilers/solc/compiler.rs
crates/compilers/src/flatten.rs
crates/compilers/tests/project.rs

Found a couple bugs while testing https://github.com/foundry-rs/foundry/pull/8159 on random contracts.
Also updated `find_svm_installed_version` to accept `&Version` instead of relying on caller stripping of build metadata.

fix(flatten): small bugs

---

crates/artifacts/vyper/src/settings.rs
crates/compilers/src/compilers/mod.rs
crates/compilers/src/compilers/multi.rs
crates/compilers/src/compilers/solc/mod.rs
crates/compilers/src/compilers/vyper/input.rs
crates/compilers/src/compilers/vyper/parser.rs
crates/compilers/src/compilers/vyper/settings.rs
crates/compilers/src/resolver/mod.rs

Vyper 0.4 added `search_paths` key which is basically equivalent to solc's `include_paths` which we are already populating during import resolution.
Adds this key to compiler input and also tries going through `paths.libs` while resolving Vyper imports.
This allows users to normally configure dependencies outside of their `src` directory (i.e. from `venv/.../site-packages` or `lib`)

feat: respect `paths.libraries` for Vyper

---

crates/artifacts/solc/src/ast/lowfidelity.rs
crates/artifacts/solc/src/ast/mod.rs
crates/artifacts/solc/src/bytecode.rs
crates/artifacts/solc/src/lib.rs
crates/artifacts/solc/src/remappings.rs
crates/artifacts/solc/src/sources.rs
crates/artifacts/vyper/src/settings.rs
crates/compilers/src/artifact_output/mod.rs
crates/compilers/src/buildinfo.rs
crates/compilers/src/cache.rs
crates/compilers/src/compile/output/contracts.rs
crates/compilers/src/compile/output/info.rs
crates/compilers/src/compile/output/mod.rs
crates/compilers/src/compile/output/sources.rs
crates/compilers/src/compile/project.rs
crates/compilers/src/compilers/mod.rs
crates/compilers/src/compilers/solc/compiler.rs
crates/compilers/src/compilers/vyper/mod.rs
crates/compilers/src/config.rs
crates/compilers/src/lib.rs
crates/compilers/src/project_util/mock.rs
crates/compilers/src/project_util/mod.rs
crates/compilers/src/report/compiler.rs
crates/compilers/src/resolver/mod.rs
crates/compilers/tests/project.rs
crates/core/src/utils.rs

These mostly only bloat code size and compilation times, which are already not great when we are already codegenning a billion structs and ASTs with serde derives
For AsRef<str>, the only change is having to specify an extra 1 (one) character (&) when using `String` so it derefs to `str`, otherwise it's the same
For AsRef<Path> it's the same as AsRef<str> when using Path/PathBuf, but it's a bit worse for string literals; but most of these functions are called with variables in the first place. except in tests which will have to use .as_ref() or Path::new
I've not removed these when using with &[] or impl IntoIterator since that does help quite a bit, e.g if you have an owning iterator of Strings, you cannot borrow inside of a map closure
I've also kept Into<PathBuf> since that makes more …

chore: remove most impl AsRef<str,Path>

---

crates/artifacts/solc/src/configurable.rs
crates/artifacts/solc/src/lib.rs
crates/artifacts/solc/src/sources.rs
crates/compilers/src/buildinfo.rs
crates/compilers/src/cache.rs
crates/compilers/src/compile/project.rs
crates/compilers/src/filter.rs
crates/compilers/src/lib.rs
crates/compilers/src/resolver/mod.rs

Allows reusing resources and just doing `retain` instead of `.into_iter().collect()` on 3 nested maps

refactor: unify sources and filtered sources

---

crates/compilers/src/cache.rs

without a span they're messages with no context

chore: improve some trace-level logs

---

crates/artifacts/solc/src/bytecode.rs
crates/artifacts/solc/src/lib.rs
crates/artifacts/solc/src/remappings.rs
crates/artifacts/vyper/Cargo.toml
crates/artifacts/vyper/src/input.rs
crates/artifacts/vyper/src/settings.rs
crates/compilers/src/artifact_output/mod.rs
crates/compilers/src/cache.rs
crates/compilers/src/compile/output/sources.rs
crates/compilers/src/config.rs
crates/compilers/src/filter.rs
crates/core/src/utils.rs

Use utils to avoid allocations, add stripping methods to ArtifactId for https://github.com/foundry-rs/foundry/pull/8294

chore: improve stripping file prefixes

---

crates/artifacts/solc/src/remappings.rs
crates/compilers/src/report/mod.rs
crates/compilers/tests/project.rs

Fix #47. One corresponding test is added. 
- Remove the code that blindly add trailing `/` when serializing `Remapping` and `RelativeRemapping`.
- Preserve the trailing `/` in the `strip_prefix` method of `Remapping`.
There are roughly two sources where `Remapping` comes from:
- Generated in `find_many` function.
- Loaded from configuration like `foundry.toml`.
When generating `Remapping` in `find_many` function, the algorithm makes sure that the `name` and `path` of every remapping are valid folders in the file system. Then, trailing `/`s are added to both `name` and `path` in the `impl From<RelativeRemapping> for Remapping` implementation.
https://github.com/Troublor/compilers/blob/93c5f46a7dd0c0d387dd94c8ea756812e2907d92/src/remappings.rs#L360-L365
When loading `Remapping` from …

Fix inconsistent trailing slash in remappings

---

crates/artifacts/solc/src/ast/mod.rs
crates/artifacts/solc/src/ast/visitor.rs

Closes https://github.com/foundry-rs/foundry/issues/7554
solc since 0.6.7 allows empty `body` on modifiers
this was incorrect in OpenZeppelin AST impl which served as a reference for our implementation https://github.com/OpenZeppelin/solidity-ast/pull/43

fix: allow empty modifier body in AST

---

crates/artifacts/solc/src/lib.rs
crates/artifacts/vyper/Cargo.toml
crates/artifacts/vyper/src/input.rs
crates/artifacts/vyper/src/settings.rs
crates/compilers/src/cache.rs
crates/compilers/src/compile/project.rs
crates/compilers/src/compilers/mod.rs
crates/compilers/src/compilers/multi.rs
crates/compilers/src/compilers/solc/compiler.rs
crates/compilers/src/compilers/solc/mod.rs
crates/compilers/src/compilers/vyper/input.rs
crates/compilers/src/compilers/vyper/settings.rs
crates/compilers/src/lib.rs
crates/compilers/src/project_util/mod.rs
crates/compilers/tests/project.rs

This refactors `Compiler` a bit moving some of the configuration methods from `CompilerInput` to `CompilerSettings`, preferring sanitization of settings during input construction instead of in `with_*` methods of version-aware input.
Instead of using JSON solc settings, I've added separate `SolcSettings` type divided into JSON and CLI settings

feat: allow passing extra cli args to solc + some cleanup

---

crates/artifacts/solc/Cargo.toml
crates/artifacts/solc/src/lib.rs
crates/compilers/src/compilers/solc/mod.rs

adds key for enabling eof which is supported by https://github.com/ipsilon/solidity/tree/eof-functions-rebased
solc allows unknown keys in settings, so setting this wouldn't break default solc. though I think it might make sense to be under a feature flag. wdyt @mattsse

feat: add `eofVersion` config option

---

crates/artifacts/solc/src/lib.rs
crates/core/src/utils.rs

Adds Prague spec.
TODO: PragueEOF support is needed.

feat: add Prague evm version

---

crates/compilers/src/cache.rs

Closes https://github.com/foundry-rs/compilers/issues/172

fix: remove outdated build infos

---

crates/artifacts/solc/src/lib.rs
crates/compilers/src/compile/output/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/8548
we've had logic for determining ignored warnings duplicated, this PR refactors it into helpers on `AggregatedCompilerOutput`

fix: unify logic for ignored warnings

---

crates/artifacts/vyper/src/settings.rs

ref https://t.me/foundry_support/55572
Vyper is a bit weird about EVM versions support, e.g. 0.4 does not support versions older than London and 0.3 never supported London at all, but this should be enough to cover basic scenarios for 0.3 and 0.4 users

feat: sanitize EVM version for vyper

---

crates/compilers/src/resolver/mod.rs

Currently, if no Vyper or Solidity compiler is available, returned error would look like:
```
Found incompatible Solidity versions:
src/a.vy  imports:
src/b.vy 
Found incompatible Solidity versions:
src/b.vy  imports:
...
```
This PR adds logic for catching case when the error is caused by missing compiler for the language

feat: more user-friendly error when no compiler is available

---

crates/compilers/src/flatten.rs
test-data/hardhat-sample/contracts/Greeter.sol

Closes https://github.com/foundry-rs/compilers/issues/183
Instead of finding line containing license in target source and adding it to the top, we find it and extract the license identifier itself

fix(flatten): update license handling logic

---

crates/compilers/src/cache.rs
crates/compilers/src/compile/output/contracts.rs
crates/compilers/src/compile/output/mod.rs
crates/compilers/src/compile/output/sources.rs
crates/compilers/src/compile/project.rs
crates/compilers/src/compilers/multi.rs
crates/compilers/src/lib.rs
crates/compilers/tests/project.rs

Closes https://github.com/foundry-rs/compilers/issues/187
Closes https://github.com/foundry-rs/compilers/issues/168
Updates `MultiCompiler` and makes solc compiler on it optional. If `svm-solc` is not activated, it is attempted to initialize solc via `Solc::new("solc")`, and if solc binary is not available in command line, it is set to None.
We could also add `svm-solc` to default features as I think people would often prefer enabling it as it's required to emulate foundry's default behavior.

feat: always provide `Default` for `MultiCompiler`

---

README.md
crates/artifacts/solc/src/ast/utils.rs
crates/artifacts/solc/src/remappings.rs

Hello
I found and fixed several spelling issues.
Br, Elias.

Docs fix spelling issues

---

crates/artifacts/solc/src/lib.rs

The default EVM version for Solidity compilers ranging from 0.4.21 to 0.5.4 is incorrectly implemented. Specifically, although the `Constantinople` hard fork had been introduced during this period, the default EVM version remains as `Byzantium`. After version 0.5.5, the default EVM version shifts to `Petersburg`. 
That is, `Constantinople` is never used as the default EVM version for Solidity compilers.
This can be confirmed by running `solc --help`, with the output indicating the default EVM version as follows:
```bash
$ solc --help
solc, the Solidity commandline compiler.
...
Allowed options:
--help               Show help message and exit.
--version            Show version and exit.
--license            Show licensing information and exit.
--evm-version version
Select desired EVM …
```

Incorrect Default EVM Version for Solidity Compiler 0.4.21-0.5.4

---

README.md

Due to the this commit:
commit bc96471cf13d1d1030e3773b29609d4fd3621579
Author: DaniPopes <57450786+DaniPopes@users.noreply.github.com>
Date:   Sat Jun 29 00:20:26 2024 +0200
chore: remove most impl AsRef<str,Path> (#157)
The interface for `hardhat()` is updated to `&Path`.

chore: fix up the README example

---

crates/artifacts/solc/src/ast/mod.rs

Fix for 2 ast node bindings
* BinaryOperation can qualify as an `expr_node!`
* Return AST Node's `function_return_parameters` should be made optional because when return is used inside modifiers, the AST generated by solc doesn't include the `function_return_parameters` field
More context:
I tried using these changes on [Aderyn](https://github.com/Cyfrin/aderyn/blob/5c483fdbf1f454ca42c1fd9b85353b0b9241c43a/aderyn_core/src/ast/ast_nodes.rs#L639C1-L645C3) for a while and haven't come across an unrecognized node since :) So I thought I'll share it with ya!

Fix: Ast Node Bindings

---

Cargo.toml
crates/compilers/Cargo.toml
crates/compilers/src/resolver/mod.rs
crates/core/src/error.rs
test-data/incompatible-pragmas/src/A.sol
test-data/incompatible-pragmas/src/B.sol
test-data/incompatible-pragmas/src/C.sol

Closes https://github.com/foundry-rs/compilers/issues/43
Adds logic to resolve which nodes actually caused the resolver failure. This provides us access to ids of actually incompatible nodes in `format_imports_list` fn. 
It will now highlight sources causing failure in red

feat: better error messages for incompatible versions

---

crates/artifacts/solc/src/configurable.rs
crates/compilers/src/artifact_output/configurable.rs
crates/compilers/src/compilers/solc/mod.rs
crates/compilers/tests/project.rs

adding support for `legacyAssembly` artifact output, https://github.com/foundry-rs/foundry/issues/8977

fix: include `evm.legacyAssembly` output

---

crates/compilers/src/compilers/mod.rs
crates/compilers/src/compilers/solc/compiler.rs
crates/compilers/src/compilers/solc/mod.rs
crates/compilers/src/compilers/vyper/mod.rs

ref https://github.com/foundry-rs/foundry/issues/8997
Adds `Solc` constructor for creating solc instances with arguments. Changes `extra_args` to being prepended to actual solc arguments instead of appended as for now.
This allows us to use eof binary through `Solc::new_with_args("docker", ["run", ... ])`
We didn't end up using those for `--eof-version`, so this shouldn't break anything. Will add a test for this in scope `--eof` flag on foundry side

feat: better extra_args handling

---

crates/artifacts/solc/src/sourcemap.rs
crates/compilers/src/report/mod.rs

Fixes https://github.com/foundry-rs/foundry/issues/8986
Looks like solc can emit partial first elements in source map which we were rejecting

fix: accept partial first sourcemap element

---

crates/compilers/src/project_util/mod.rs

Required for https://github.com/foundry-rs/foundry/pull/7909
Related: https://github.com/foundry-rs/foundry/blob/32863e7b19bc07304ad0cac2e2b018fdde295f94/crates/forge/bin/cmd/compiler.rs#L318-L319
Allow adding Vyper sources with `add_raw_source` w/ `.vy` / `.vyi` extension so it can be compiled as part of the script

chore: allow adding vyper sources with `add_raw_source` w/ `.vy` / `.vyi` extension

---

crates/compilers/src/compilers/vyper/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/9123
I've done similar workaround for rc before. For semver we need those to be prepended by a dash.
PEP440 pragmas are still might not be parsed correctly but this is not a showstopper as we're just ignoring them right now, and user would see a vyper error in case of mismatch.

fix: correctly handle b as pre-release in Vyper version

---

crates/artifacts/solc/src/lib.rs

Ref https://github.com/foundry-rs/foundry/issues/9322#issuecomment-2480484349
https://github.com/ethereum/solidity/issues/15576#issuecomment-2480385494
Set inliner to None since it is properly supported from 0.8.5 version( see `Standard JSON: Properly allow the inliner setting under settings.optimizer.details` https://soliditylang.org/blog/2021/06/10/solidity-0.8.5-release-announcement/)

fix: sanitize `settings.optimizer.details.inliner`

---

crates/compilers/src/lib.rs
crates/compilers/src/resolver/mod.rs

This should go over all nodes vs just the first one and its dependencies

fix: `collect_contract_names`

---

crates/compilers/src/resolver/parse.rs

Removed in https://github.com/foundry-rs/compilers/pull/215
Fixes after bump https://github.com/foundry-rs/foundry/issues/9349

fix: re-add version regex parsing

---

crates/compilers/src/resolver/mod.rs

This pull request addresses a minor grammatical issue in the project documentation regarding the description of the dependency resolution algorithm. Specifically, the following sentence:
> Finding all dependencies is fairly simple, we're simply doing a DFS, starting the source contracts.
The sentence is missing the preposition "from," making it grammatically incorrect and slightly harder to read. The corrected version is:
> Finding all dependencies is fairly simple, we're simply doing a DFS, starting **from** the source contracts.
While this is a small change, improving the grammar enhances the readability and professionalism of the documentation. Clear documentation is especially important for developers who rely on it to understand the dependency resolution logic and its implementation. …

Fix minor grammatical issue in project documentation

---

crates/compilers/src/compilers/restrictions.rs

Inner restrictions are not being merged correctly right now

fix: correctly merge restrictions

---

crates/artifacts/solc/src/lib.rs

Currently, `EvmVersion` won't get deserialized for `spuriousdragon` and `tangerinewhistle`. 
This can be reproduced using:
```
cast run 0x6b5ca68eb4c4b38690ec12ba9f85409b618759646e50ab53b28f9d67f74978fc --rpc-url=https://rpc.ankr.com/eth --evm-version spuriousDragon
Error: failed to extract foundry config:
foundry config error: Unknown evm version: spuriousdragon for key "default.evm_version" in RunArgs for setting `evm_version`
```
Solution:
Handle camel case and lowercase

fix: EvmVersion `from_str`

---

crates/artifacts/artifacts/Cargo.toml
crates/artifacts/solc/Cargo.toml
crates/artifacts/solc/src/remappings/find.rs
crates/artifacts/solc/src/remappings/mod.rs
crates/artifacts/solc/src/sources.rs
crates/compilers/Cargo.toml
crates/core/Cargo.toml
crates/core/src/utils/mod.rs
crates/core/src/utils/re.rs
crates/core/src/utils/wd.rs

When importing sub crates directly (like artifacts) we don't need regex, walkdir, and other deps.
No functional changes intended.

feat: add more features to reduce dependencies

---

crates/compilers/src/artifact_output/mod.rs
crates/compilers/src/compile/project.rs
crates/compilers/src/lib.rs
crates/compilers/src/resolver/mod.rs

Closes https://github.com/foundry-rs/foundry/issues/9722
This PR introduces a concept of "primary" profile. Primary profile is the one which we've chosen for input source when analyzing it on its own (i.e not as a dependency of other contract). That way `Counter.json` would always correspond to an artifact compiled with the default profile if it was possible.

feat: better artifact filenames for different profiles

---

crates/artifacts/solc/src/error.rs

Before + after
Incredibly cursed thanks to the awesome consistent implementation in solc

fix: handle displaying multiline errors correctly

---

crates/compilers/src/flatten.rs

Closes https://github.com/foundry-rs/foundry/issues/9788
ref https://github.com/foundry-rs/foundry/issues/9788#issuecomment-2633799377
Instead of sorting by path, firstly attempts sorting by filenames

fix: ordering for flattener

---

crates/compilers/src/compile/output/info.rs

Ref: https://github.com/foundry-rs/foundry/pull/9770#discussion_r1934652943
Smol convenience fn for `ContractInfo` to retrieve the `Path`.

feat: impl `.path(&self)` for `ContractInfo`

---

crates/artifacts/solc/src/ast/mod.rs
crates/artifacts/solc/src/ast/visitor.rs
crates/compilers/src/flatten.rs
crates/compilers/tests/project.rs

- ref https://github.com/foundry-rs/foundry/issues/9876: add ErrorDefinition as part of SourceUnitPart group

fix: allow top level event declarations

---

crates/artifacts/solc/src/lib.rs

fix: update normalization

---

Cargo.toml
crates/artifacts/solc/Cargo.toml
crates/artifacts/solc/src/sources.rs
crates/compilers/Cargo.toml
crates/compilers/src/buildinfo.rs
crates/compilers/src/compile/output/mod.rs
crates/core/Cargo.toml
crates/core/src/utils/mod.rs

Closes https://github.com/foundry-rs/compilers/issues/259.

perf: switch md5 to xxhash

---

crates/artifacts/solc/src/ast/misc.rs

Trivial patch. The new variant `transient` seems missing.

Support `transient` in `StorageLocation`

---

cliff.toml

Replaced the outdated or broken link to the Tera template engine documentation in cliff.toml with the current one: https://keats.github.io/tera/docs/#introduction
This change helps users quickly find up-to-date documentation for the template syntax used in the changelog configuration.

fix: update Tera documentation link in cliff.toml

---

crates/artifacts/solc/src/ast/mod.rs

Trivial patch.
Reproduce:
```bash
echo '{"language":"Solidity","sources":{"test.sol":{"content":"contract TT {\\n    function main() public {}\\n}"}},"settings":{"stopAfter":"parsing","optimizer":{"enabled":false,"runs":200},"outputSelection":{"*":{"":["ast"],"*":[]}},"viaIR":true,"libraries":{}}}' | solc --standard-json
```
Since there is no semantics analysis when stopping after parsing, `scope` along with a few other fields are not available and this PR marks all `scope` to be optional.

Some fields are optional during `"stopAfter":"parsing"`

---

crates/compilers/src/artifact_output/mod.rs
crates/compilers/src/compilers/solc/compiler.rs
crates/compilers/src/resolver/mod.rs

I got a `ERROR` log when using `forge flatten` with no extra message, and the error itself gets ignored with a fallback

chore: clean up error! calls

---

crates/artifacts/solc/Cargo.toml
crates/artifacts/solc/src/lib.rs
crates/compilers/src/compilers/solc/mod.rs

EOF has been deprecated in Foundry
Remove unused `serde_repr` dependency

debt: remove EOF version field

---

crates/artifacts/solc/Cargo.toml
crates/artifacts/solc/src/bytecode.rs

ref [#10596](https://github.com/foundry-rs/foundry/pull/10596#discussion_r2161689091)

chore: upstreamed  `strip_bytecode_placeholders` from foundry

---

crates/artifacts/vyper/src/settings.rs
crates/compilers/tests/project.rs

Adds support for Vyper 0.4.3 which now defaults to `prague`

chore: bump vyper to 0.4.3 which adds support for `prague`

---

crates/compilers/src/artifact_output/configurable.rs

This commit removes a redundant check for assembly in the is_dirty method, leaving only a single, correct check for assembly. No other logic was changed.

Remove duplicate assembly check in is_dirty

---

crates/artifacts/solc/src/sources.rs
crates/compilers/src/cache.rs
crates/compilers/src/compile/output/mod.rs
crates/compilers/src/compile/project.rs
crates/compilers/src/compilers/mod.rs
crates/compilers/src/compilers/solc/compiler.rs
crates/compilers/src/compilers/vyper/mod.rs
crates/compilers/src/compilers/vyper/parser.rs
crates/compilers/src/resolver/mod.rs
crates/compilers/src/resolver/parse.rs

`#[instrument]` and clean up. No functional changes intended.

chore: add more instrumentation

---

crates/compilers/src/resolver/mod.rs

ref https://github.com/foundry-rs/foundry/issues/11149 
- handle import error for non existent files in same way as resolve_import_and_include_paths - trace and leave solc to bail
Forge build output changes from
```bash
[⠃] Compiling...2025-07-31T06:24:58.330480Z ERROR foundry_compilers_artifacts_solc::sources: error="/badpath/B.sol": No such file or directory (os error 2)
[⠊] Compiling...
Error: failed to resolve file: "/badpath/B.sol": No such file or directory (os error 2); check configured remappings
--> /tmp/foundry-issue/src/Counter.sol
/badpath/B.sol
```
to (on missing file)
```bash
[⠃] Compiling...2025-07-31T06:24:55.678474Z ERROR foundry_compilers_artifacts_solc::sources: error="/badpath/B.sol": No such file or directory (os error 2)
[⠊] Compiling...
[⠒] Unable to resolve …
```

fix: consistent handle of unresolved imports

---

.github/CODEOWNERS

Updates `CODEOWNERS` to improve visibility as this is a direct dependency of Foundry

chore: update `CODEOWNERS` to improve visibility

---

Cargo.toml
crates/compilers/Cargo.toml
crates/compilers/src/cache/iface.rs
crates/compilers/src/compilers/solc/mod.rs
crates/compilers/src/lib.rs
crates/compilers/src/resolver/parse.rs

No gain from using the minor crates directly

chore(deps): switch to solar meta crate

---

crates/artifacts/solc/src/lib.rs

Introduced in 0.7.3: https://github.com/ethereum/solidity/releases/tag/v0.7.3

fix: sanitize `stopAfter`

---

crates/compilers/src/cache.rs

Making more readable and improving tracing. No functional changes.

refactor: cache/is_dirty impls

---

crates/artifacts/solc/src/sources.rs
crates/compilers/src/config.rs
crates/compilers/src/flatten.rs
crates/compilers/src/resolver/mod.rs

Cache entries are keyed by absolute path relative to project root, but it's possible to construct and pass in Sources from a relative path, such as CLI argument in `forge lint`/`forge eip712`...
In these cases the path will be relative and will always be a cache miss. This includes the path's imports, which get resolved as relative to the initial path rather than root now with Solar.
Make all paths in Sources absolute when constructing Graph so that this change propagates through the entire compilation process.
I couldn't find a reproducer in today's stable/nightly Foundry, however making `config.solar_project()` use `project()` instead of `ephemeral_project()` will reproduce the behavior explained above.
With this change, `solar_project` will almost never call to solc.

fix: make sources' paths absolute

---

crates/artifacts/solc/Cargo.toml
crates/artifacts/solc/src/remappings/find.rs

No logic changes except: 2nd commit removes walkdir and doesn't sort by file name anymore because order doesn't matter when we run it in parallel

perf: parallelize Remapping::get_many

---

Cargo.toml
crates/artifacts/solc/Cargo.toml
crates/artifacts/solc/src/bytecode.rs

Collect all references at once, then replace all of them with a simple copy. We can avoid using `string.replace` which creates a copy and is not vectorized because the placeholders are the same length as an address (40 bytes in hex).

perf: improve linking implementation
