foundry-rs/compilers

- .github/workflows/ci.yml
Main branch is main, not master
> chore: run ci on main

- Cargo.toml
> chore: bump solang parser to 0.3.3

- src/lib.rs
- tests/project.rs
ref https://github.com/gakonst/ethers-rs/pull/2730
> fix: also cleanup build info dir

- src/artifacts/mod.rs
Adds helper method to strip path prefixes from `Libraries` object, I'll need this for https://github.com/foundry-rs/foundry/pull/7027
> Helper method for `Libraries`

- src/artifacts/error.rs
Fallback to the first line of the formatted message if the `message` field is empty
Fixes (probably) https://github.com/foundry-rs/foundry/issues/7100
> fix: empty error message formatting

- src/artifacts/error.rs
Closes https://github.com/foundry-rs/foundry/issues/5446
> fix: don't bother formatting old solc errors

- src/artifact_output/configurable.rs
Closes https://github.com/foundry-rs/foundry/issues/4809
> fix: make solc emit ir with extra_output_files=ir

- src/cache.rs
- src/flatten.rs
> chore: use Path::new instead of PathBuf::from

- src/artifacts/output_selection.rs
Ref https://github.com/foundry-rs/foundry/pull/7334#discussion_r1518557879
with that helper it will be `OutputSelection::common_output_selection(["abi".to_string()])`
> helper for `OutputSelection`

- README.md
> chore: remove main fn

- src/lib.rs
> chore: warn unused

- src/cache.rs
ref https://t.me/foundry_support/53263
when running `forge test` with dirty files, we firstly do a ABI-only compilation which handles dirty files and removes their artifacts from disk. however, we do not write updated cache file as this compilation is ephermal, thus we are ending up with cache file containing artifacts which does not exist, and this causes issues when compiling project normally.
this could be fixed by only removing dirty artifacts when writing cache, but I think this doesn't give us much benefit as we'll overwrite those anyway.
Also changed flow a bit to ensure that we corretly handle graph resultion error when detecting dirty sources.
> fix: do not remove dirty artifacts from disk

- src/sourcemap.rs
Compresses `SourceElement` from 40 to 16 bytes. Solc uses `int` for numbers so 32 bits should be fine to use 32 bit numbers or a bit less.
Source maps can be in the 100K elements for 1MB contracts, so this should help a bit with memory consumption.
> perf: reduce size of source map

- Cargo.toml
- src/compile/mod.rs
- src/resolver/mod.rs
- tests/project.rs
ref https://github.com/foundry-rs/foundry/issues/8062
ref https://t.me/foundry_support/54144
introduced in https://github.com/foundry-rs/compilers/pull/128
> fix: version resolution

- Cargo.toml
- crates/artifacts/solc/Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/utils.rs
> chore: cleanup workspace deps

- crates/compilers/src/artifact_output/mod.rs
- crates/compilers/src/compilers/mod.rs
idk if this changes anything, make the lock a separate variable
> chore: clarify version cache lock

- Cargo.toml
Bump alloy primitives and json-abi to `0.8`
> chore(deps): bump alloy

- crates/artifacts/solc/src/sourcemap.rs
Ref https://github.com/foundry-rs/foundry/issues/8877
No functional changes
> chore: improve error handling in source map parsing

- crates/artifacts/solc/src/remappings.rs
- crates/compilers/src/artifact_output/configurable.rs
- crates/compilers/src/artifact_output/mod.rs
Hello
I fixed several minor typos.
> docs: fix typos

- crates/artifacts/solc/src/output_selection.rs
- crates/compilers/src/artifact_output/configurable.rs
- write contents in `Contract.legacyAssembly.json` file
> chore: proper generate legacy asm extra output file

- crates/compilers/src/project_util/mod.rs
should fix ci failure https://github.com/foundry-rs/compilers/actions/runs/11889326739/job/33125668737
> fix(tests): always try installing pinned solc

- crates/compilers/src/resolver/parse.rs
smol typo, should close https://github.com/foundry-rs/foundry/issues/9365
> fix: imports regex fallback

- crates/artifacts/solc/src/lib.rs
> fix: missing check for normalization

- crates/artifacts/solc/src/lib.rs
Hi! I updated the file extension to ensure compatibility with the system requirements. This change maintains functionality while following the expected file format standards.
> chore: update file extension for compatibility

- CONTRIBUTING.md
> fix Update CONTRIBUTING.md

- Cargo.toml
- deny.toml
Required in https://github.com/foundry-rs/foundry/pull/10454
> chore(deps): bump alloy 1.0

- crates/artifacts/solc/src/ast/lowfidelity.rs
This PR adds a few missing NodeTypes for the node AST.
> Add missing node types

- Cargo.toml
- crates/compilers/Cargo.toml
Bump outdated dependencies as preparation for next release
> chore: update deps

- CHANGELOG.md
- Cargo.toml
- README.md
pushing to main directly is disabled
> chore(deps): bump to 0.18.3
